<?php require('template/header.phtml');  ?>
<input type="hidden" value="<?php echo $_SESSION['userID'] ?>" id="userID">
<div class="container">

<div class="col-lg-offset-0">

    <div id="myList" style="padding-top: 130px; padding-bottom: 120px" ;>

        <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
            <?php
                if(empty($view->basket) and !(isset($_GET['thankYou']))) {
                    echo '<p  style="text-align: center; font-size: 20px;">
                            Your basket is empty. Feel free to <a style="color: #2b669a" href="../shopList.php">
                            <b>check</b></a> out our latest offers!
                          </p>';

                }
                else {

                    echo '

                        <nav class="nav navbar-fixed">
                        
                        <div class="col-xs-12">
                            <button class="clearCart btn btn-danger">Clear Cart</button>                           
                            <input type="submit" class="btn btn-success pull-right" name="checkOut" value="CheckOut">
              
                        </div>
                        </nav>';


                    $totalPrice = ""; // variable for price
                    $finalPrice = "";
                foreach ($view->basket as $basketData) {

                    $basketBookId = $basketData->getBookID();
                    $book = $view->booksDataSet->searchBook('idBook', $basketBookId);
                    $totalPrice += ($basketData->getQuantity() * $book->getPrice());
                    $finalPrice += $totalPrice;

                    echo '
                <div id="bookSet'.$basketData->getBookID().'" class="bookSet col-sm-12" data-id="'.$basketData->getIdBasket() .'">
                        <p>' . '<img src="../images/' . $book->getPhotoName() . ' " alt="no pic" />' . '</p>
                        <p><b>Name:</b> ' . $book->getBookName() . ' </p>
                        <p><b>Available: </b>' . $book->getNumberInStock() . ' </p>
                        <p><b>Price: £</b>' . $book->getPrice() . ' </p>
                        <p><b>Total price: £</b>' . ($basketData->getQuantity() * $book->getPrice()) . '</p>
                        <p><b>Quantity:</b>                   
                        <a style="color: green;" class="removeFromCartMinus glyphicon glyphicon-minus-sign" data-quantity="itemQuantity' .
                            $basketData->getBookID(). '" data-id=" '. $basketData->getBookID() .'">     
                        <span id="itemQuantity' . $basketData->getBookID(). '" > ' . $basketData->getQuantity() . '</span> </a>                 
                         <a style="color: green;" class="addToCartPlus glyphicon glyphicon-plus-sign" data-quantity="itemQuantity' .
                            $basketData->getBookID(). '" data-id=" '. $basketData->getBookID() .' "></a>
                         </p>
                      <p>' . '<button data-id="' . $basketData->getIdBasket() . '" class="removeFromCart"><b>Remove</b><span class="glyphicon glyphicon-shopping-cart"></span></button>' . ' </p>
                </div> ';
                }

                echo '<p><b>Total price £: </b>' . $finalPrice . ' </p>';
            }

            if(isset($_GET['thankYou'])){

                    echo '<h3 class="text-center text-success">Thank you for shopping with us!</h3>';
            }

            ?>

        </form>

    </div>
</div>
</div>

<?php require('template/footer.phtml');  ?>
