<?php require('template/header.phtml') ?>

<div id="myCarousel" class="carousel slide" data-ride="carousel">

    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="item0 active"></li>
        <li data-target="#myCarousel" data-slide-to="1" class="item1"></li>
        <li data-target="#myCarousel" data-slide-to="2" class="item2"></li>

    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="images/carousel2.jpg" alt="Image">
                <div class="container">
                    <div class="carousel-caption">
                        <?php
                        if(!(isset($_SESSION['userID']))){
                            echo ' 
                        <h3>Become a member</h3>
                        <p>
                        <a class="btn btn-lg btn-primary" href="../register.php" role="button">Sign Up today</a>
                        </p>';
                        }
                        ?>
                    </div>
                </div>
        </div>

        <div class="item">
            <img src="images/exploreLibrary3.jpg" alt="Image">
            <div class="container">
                <div class="carousel-caption">
                    <h3>Explore our library</h3>
                    <p><a class="btn btn-lg btn-primary" href="../shopList.php" role="button">Find out more!</a>
                    </p>
                </div>
            </div>
        </div>

        <div class="item">
            <img src="images/gift2.jpg" alt="Image">
            <div class="container">
                <div class="carousel-caption">
                    <h3>Send a gift</h3>
                    <p><a class="btn btn-lg btn-primary" href="../shopList.php" role="button">Send a book</a>
                    </p>
                </div>
            </div>
        </div>

    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>


<div class="container marketing">

    <div class="row">
        <div id="marketing" align="center" class="col-lg-6 col-sm-6">
            <img class="img-circle" src="images/exploreLibrary3.jpg" alt="Generic placeholder image" width="140" height="140">
            <h2>Reading Shapes You</h2>
            <p>Explore the world of books with just a single click.
                MyBook online Library has a vast collection of texts for every person and for every field you might be
                eager to explore. Enjoy!</p>
            <p><a class="btn btn-info" href="../shopList.php" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->

        <div id="marketing" align="center" class="col-lg-6">
            <img class="img-circle" src="images/gift2.jpg" alt="Generic placeholder image" width="140" height="140">
            <h2>There is no better gift</h2>
            <p>
                Not sure what gift to buy for a friend, a family member or a colleague? MyBook online Library comes with
                the solution. Check our variety of books that you one to give as a present and for there MyBook online
                Library delivers the book or books without any additional cost.
            </p>
            <p><a class="btn btn-info" href="../shopList.php" role="button">View details &raquo;</a></p>
        </div>
    </div>

<!-- Carousel changing item image by his own -->
<script>
    $(document).ready(function(){
        // Activate Carousel
        $("#myCarousel").carousel();

        // Enable Carousel Indicators
        $(".item1").click(function(){
            $("#myCarousel").carousel(0);
        });
        $(".item2").click(function(){
            $("#myCarousel").carousel(1);
        });
        $(".item3").click(function(){
            $("#myCarousel").carousel(2);
        });

        // Enable Carousel Controls
        $(".left").click(function(){
            $("#myCarousel").carousel("prev");
        });
        $(".right").click(function(){
            $("#myCarousel").carousel("next");
        });
    });
</script>

<?php require('template/footer.phtml') ?>
