<div id="response" style="font-size: 20px; width: 100%; position: fixed; margin-bottom: 15px;"  class="bg-success text-center text-success"></div>
<?php require('template/header.phtml'); ?>
<?php
    date_default_timezone_set('Europe/London');
    $view->product = $_SESSION['book'];
?>

<div class="container" id="shop">

    <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">

    <div class="row">
        <div class="col-sm-12">
            <?php

            echo '<a href="product.php?id='. $view->product->getIdBook() .'"> <div id="singleBook">
                        <p style="float: right; font-size: 25px; color: #4876FF;"><b><i> ' . $view->product->getBookName() . ' </i></b></p>
                        </div></a>';
            ?>

            <div class="col-xs-12 col-sm-6 text-right">

                <?php
                echo '<a href="product.php?id='. $view->product->getIdBook() .'"> <div id="aloneBook">
                        <p>' . '<img src="images/'. $view->product->getPhotoName()  . ' " alt="no pic" />' . '</p> </div></a>';
                ?>

            </div>
            <div class="col-xs-12 col-sm-6">

                <?php
                echo '<a href="product.php?id='. $view->product->getIdBook() .'"> 
                    <div id="singleBook">
                        <p><b>Author:</b> ' . $view->product->getAuthor() . ' </p>
                        <p><b>Available:</b> ' . $view->product->getNumberInStock() . ' </p>
                        <p><b>Price: £</b>'.$view->product->getPrice() . ' </p>
                    </div></a>';
                ?>

                <p><b>Quantity:</b></p>
                <p><input type="hidden" value=" <?php echo $view->product->getIdBook() ?>" name="productID"></p>
                <p><input type="number" name="quantityPerItem" min="1" max=" <?php echo $view->product->getNumberInStock() ?>  "></p>
                <p><button type="submit" name="addMoreItems">Add to Basket</button></p>

            </div>
        </div>
    </div>

    </form>

    <h2 class="text-center text">Tell us what you think?</h2>
    <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
        <?php
        if(empty($view->review))
        {
            echo '<p class="text-center text-info">"No comments for this book"</p>';
        }
        foreach ($view->review as $reviewData) {
            echo '<div class="review-box">
                        <a href="../product.php?id='. $reviewData->getIdBook() .'">
                        <p><b> ' . $reviewData->getUserEmail() . ' </b></p>
                        <p class="text-right"><i> ' . $reviewData->getDateTime() . ' </i></p>
                        <p> ' . $reviewData->getComments() . ' </p></a>
                  </div>';
        }
        ?>
    </form>

    <?php
    echo '<form action="../product.php?id=' . $view->product->getIdBook() . '" method="post">
    <div id="comment">
        <input type="hidden" name="ids" value" ' . $view->product->getIdBook() . ' ">
        <input type="hidden" name="date" value="" ' . date('Y-m-d') . '">
        <textarea name="message" class="text-center" placeholder="Share your opinion..."></textarea></br>
        <button class="btn btn-primary" name="submitCom" type="submit">Comment</button>
    </div>
        </form>';
    ?>

</div>

<?php require('template/footer.phtml'); ?>
