<?php ?>

    <div class="container" style="margin-top: 180px; text-align: center">
        <div class="row">
        <div class="col-xs-12 col-sm-12 col-lg-offset-4 text-center">

            <form role="form" action="../resetPassword.php" method="post">

            <input type="hidden" name="eMailReset" value="<?php echo $_GET['eMail'] ?>">
            <input type="password" name="passwd">
            <input type="password" name="checkPassword">

            <button type="submit" name="resetPasswdBtn">Reset Password</button>

            </form>

        </div>
        </div>
    </div>

<?php ?>