</div>

<div class="container-fluid">
    <div class="footer">

        <p>Posted by: <a href="#">MyBooks</a></p>
        <p>Contact information: <a href="mailto:m.r.blaga@edu.salford.ac.uk">Send E-mail</a>.</p>
        <p>
            <a href="#">
                <span class="glyphicon glyphicon-copyright-mark"></span>
            2016 MyBooks</a> &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms and Conditions</a>
        </p>
        <p class="pull-right"><a style="color: whitesmoke;" href="#"><b>Back to top<b></a></p>
        </div>

    </div>
</div>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<!--<script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>-->
<!--<script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>-->



<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/js.js"></script>
<!--if (isset($view->errMessage)){-->
<!--//    echo "<script>-->
<!--//            $('#myModal').modal('show');-->
<!--//           </script>";-->
<!--//}-->
<!--//?>-->

</body>
</html>